### PR TITLE
[PP-1507] Present sorts as links with palaceproject.io namespaced sort rels.

### PR DESCRIPTION
**Pull request by dbernstein**
## Description
This is a first pass at the ticket below: 

I added two new elements to the [terms namespace](https://www.notion.so/lyrasis/palaceproject-io-terms-namespace-572089bd44404cf395f02b6b78361fe4). 

Then I implemented them here for the OPDS 1 feed and OPDS 2 feeds.
I'm adding in new links for sorts based on the new namespace terms while leaving the current approach with facets in place for backward compatibility.   

The OPDS2 feed adds a new sort link and removes the old "Sort by" facet group since as far as I know, no one is using the OPDS2 feed.

The new sort links will appear just below the root.   The old sorting links formatted using the facet groups will remain in place until we we're ready to remove them.  You can expect something like the following:
```
<feed ... xmlns:palace="http://palaceproject.io/terms/properties/"... >
...
   <link  url="https://link-to-sorted-set-by-x" rel="http://palaceproject.io/terms/rel/sort" title="Sort by X"  />
   <link  url="https://link-to-sorted-set-by-y" rel="http://palaceproject.io/terms/rel/sort" title="Sort by Y"  />
   <link  url="https://link-to-sorted-set-by-z" rel="http://palaceproject.io/terms/rel/sort" title="Sort by Z"  palace:active-sort="true"  />

...
</feed>
```
I'm not sure if this is the right approach or whether it would be cleaner to do a more extensive refactor.  

I'd like feedback  on 1) the new terms and how they appear in the feed: is this what the clients would find useful?  2) should I be refactoring the FeedData class to remove the "Sort by" facet group all together?  Or should we do that as a later revision once the client apps start using OPDS2? 

## Motivation and Context
https://ebce-lyrasis.atlassian.net/browse/PP-1507

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by dbernstein** [comment]
@mauricecarrier7 and @io7m :  I've updated the description above to include what you can expect to see in the revised feed re new sorting links.  Let me know if the approach I took is going to work for you on the client end.  An of course if you'd like me to change anything, don't hold back.

**Comment by io7m** [comment]
I can't see any obvious reason why this would be a problem.

**Comment by mauricecarrier7** [comment]
Same, looks good to me. I'm not clear on the extent of what will need to change when we move to OPDS2, but holding on major refactoring until then sounds like a good approach.

**Comment by dbernstein** [comment]
I created a follow on ticket to refactor when we remove sorting facets altogether.

**Review by jonathangreen — APPROVED** [review]

**Pull request merged**
