### PR TITLE
PP-159 CDN feed urls

### PR DESCRIPTION
**Pull request by RishiDiwanTT**
## Description
CDN urls options are available for OPDS1 and OPDS2 feeds

The feed only cdnify's urls if explicitly asked to, like the links to other feeds
- search url
- contributor url
- facet url
- etc..
Any action oriented url is not cdn'd, eg. borrow links

CDN options are picked up from the environment
The Readme has been updated to reflect the new environment variables

## Motivation and Context
We should have CloudFront CDN caching for the OPDS 2 crawlable feeds so our systems are not negatively impacted when the feeds are harvested.

## How Has This Been Tested?
Unit tests have been updated for the new functionality
OPDS1 and 2 feeds were manually tested locally

## Checklist

- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jonathangreen** [comment]
@RishiDiwanTT I'd like to explore the possibility of a different approach here.

Ideally, I'd like the application not to have to re-write URLs like this, but to make the CDN caching transparent to the application. 

We can point cloudfront at our ALB, then serve the application via cloudfront. We need to do some investigation about how we can configure the cloud-front distribution, ideally we would only cache a few feeds at first. But the idea would be to eventually serve all non-authenticated requests via cloudfront.

I've not used cloudfront as a cache like this before, I've used fastly, so I'm not sure how much configuration cloudfront offers us, but I think we should do a bit of investigation here.

**Comment by jonathangreen** [comment]
Going with the approach of serving all our application URLs via CDN cache gives us a lot of flexibility to serve as many of our static URLs via a cache though.

**Comment by RishiDiwanTT** [comment]
> Going with the approach of serving all our application URLs via CDN cache gives us a lot of flexibility to serve as many of our static URLs via a cache though.

Going through cloudfront in such a manner would mean we need no changes in the application code.

**Comment by jonathangreen** [comment]
Agreed @RishiDiwanTT, the only app side changes we may need, are to change the caching headers we send out to cloudfront, to make sure the correct things are being cached. Thats why I was surprised to see this PR 😄

**Comment by RishiDiwanTT** [comment]
Closing this PR in favour of having this solved through a terraform deployment

**Pull request closed without merging**
