### PR TITLE
webpub manifest parser set to 3.0.1

### PR DESCRIPTION
**Pull request by RishiDiwanTT**
## Description
Change: https://github.com/ThePalaceProject/webpub-manifest-parser/pull/103

## Motivation and Context
Recent changes to the webpub parser needed to be included into the CM.

## How Has This Been Tested?
Unit tests have been run.

## Checklist

- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by io7m** [comment]
There's a test failure but only on one specific version. Suggests the test might be fragile... Going to try to trigger the action again.

**Comment by RishiDiwanTT** [comment]
> There's a test failure but only on one specific version. Suggests the test might be fragile... Going to try to trigger the action again.

Ran this locally on 3.10 to make sure. The tests all passed.

**Comment by jonathangreen** [comment]
I started CI rerunning, it does seem that failure is likely unrelated.

**Review by io7m — APPROVED** [review]
Seems fine. :+1:

**Pull request merged**
