### PR TITLE
Playback time tables are independent of related tables. (PP-1044)

### PR DESCRIPTION
**Pull request by tdilauro**
## Description

- Removes dependency on related identifier, collection, and library tables from the audio playback time entry (from clients) and summary tables.
- Removes constraints that require the associated keys not to be null.
- Captures the identifier urn, collection name, library name, isbn, and title at multiple points along the way.
- Adds tests to verify this functionality.

## Motivation and Context

Need to be able to remove collections, libraries, and identifiers without losing tracked playback time.

[Jira [PP-1044](https://ebce-lyrasis.atlassian.net/browse/PP-1044)]

## How Has This Been Tested?

- New tests to verify functionality.
- Performed tests in local dev environment.
- [CI tests](https://github.com/ThePalaceProject/circulation/actions/runs/8351483916) pass for associated branch.

## Checklist

- N/A - I have updated the documentation accordingly.
- [X] All new and existing tests passed.

[PP-1044]: https://ebce-lyrasis.atlassian.net/browse/PP-1044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by jonathangreen — APPROVED** [review]
This looks good 👍🏻 

I'm still a bit confused if we need to be keep track of `identifier_id`, `collection_id` and `library_id`, rather then serializing them immediately, but I'll defer to your expertise here, I haven't delved fully into the playtime entry tracking.

**Comment by jonathangreen** [comment]
FYI: Just approved https://github.com/ThePalaceProject/circulation/pull/1734 and it had a DB migration as well. So we'll need to coordinate the merging of these two PRs, since the DB migrations will conflict.

**Comment by jonathangreen** [comment]
I've been reading through the playtime tracking code, I think its my first stroll through that part of the codebase. I see now what you mean about entries being merged into summaries.  This one looks good to me 🎸.

**Comment by tdilauro** [comment]
I coordinated with @dbernstein on merging this. He will refit the migration on #1734 now that this one has been merged.

**Pull request merged**
