### PR TITLE
Add more files to mypy configuration

### PR DESCRIPTION
**Pull request by jonathangreen**
## Description

While code reviewing https://github.com/ThePalaceProject/circulation/pull/652 I noticed we can probably add a few more files to our mypy config without causing any more type errors.

After this PR, all our code is covered by mypy, except for the files specifically in the `exclude` list. The `exclude` list is quite long, but we can slowly work on knocking files off this list now. 

The only code changes included in this PR is the removal of a number of `# type: ignore` comments, that mypy complained were unnecessary. `error: Unused "type: ignore" comment`.

## Motivation and Context

Before this PR:
```
Success: no issues found in 269 source files
```

After this PR: 
```
Success: no issues found in 380 source files
```

## How Has This Been Tested?

Running mypy locally

## Checklist

- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jonathangreen** [comment]
@io7m Requesting a review from you here since it looks like most of the `type: ignore` comments I removed came in as part of your test refactoring. It seems likely that the work in #652 made them unnecessary, but I want to get your ✅ before removing them. 

@pcustic Requesting a review from you since you are our mypy czar after the work you did in #652 😄

**Comment by io7m** [comment]
I think almost every `type: ignore` I added was down to the CM not having the appropriate annotations yet. If the type checking passes without them now, I'm happy to have any of them removed.

**Review by io7m — APPROVED** [review]
These look fine to me!

**Review by pcustic — APPROVED** [review]
Yeah, this seems fine 👍  the less `type: ignore`s the better!

**Comment by pcustic** [comment]
> @pcustic Requesting a review from you since you are our mypy czar after the work you did in #652 😄

😂

**Comment by pcustic** [comment]
> @pcustic Requesting a review from you since you are our mypy czar after the work you did in #652 😄

😂

**Comment by pcustic** [comment]
> @pcustic Requesting a review from you since you are our mypy czar after the work you did in #652 😄

😂

**Pull request merged**
